/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

public class App {

    public static void main(String[] args)
    {
        String trueFilePath = "./src/main/resources/recentquotes.json";
        String trueURLPath = "https://ron-swanson-quotes.herokuapp.com/v2/quotes";

        try
        {
//            System.out.println(Quotes.readFromFile(path));

            System.out.println(Quotes.readFromAPI(trueURLPath, trueFilePath));

        }
        catch (Exception error)
        {
            System.err.println(error);
        }

    }
}
